server:
  port: 8080


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

logging.level:
    root: info
    org.springframework: info
